---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4892776043-JU8UdSezXn1c4gPMLHWuagB6YCh0asVYRlSPIGE
:access_token_secret: 0x8emnOFW5v4n4ukrHASir5RHClKHHHjB2UuoCrCxfYcC
